---
title: "R Notebook"
output: html_notebook
---

```{r}
pacman::p_load(pacman, dplyr, GGally, ggplot2, ggthemes, 
  ggvis, httr, lubridate, plotly, rio, rmarkdown, shiny, 
  stringr, tidyr) 


library(datasets)  # Load base packages manually
```

```{r}

# LOAD DATA

head(mtcars)

cars <- mtcars[, c(1:4, 6:7, 9:11)]  # Select variables
head(cars)

```

```{r}
# COMPUTE PCA

# For entire data frame
pc <- prcomp(cars,
        center = TRUE,  # Centers means to 0 (optional)
        scale = TRUE)   # Sets unit variance (helpful)


```

```{r}
# To specify variables

pc <- prcomp(~ mpg + cyl + disp + hp + wt + qsec + am +
        gear + carb, 
        data = mtcars, 
        center = TRUE,
        scale = TRUE)

```


```{r}
# Get summary stats
summary(pc)
```
```{r}
# Screeplot for number of components
plot(pc)
```
```{r}
# Get standard deviations and rotation
pc
```
```{r}
# See how cases load on PCs
predict(pc) %>% round(2)
```



```{r}
# Biplot of first two components
biplot(pc)
```

```{r}
# Clear environment
rm(list = ls()) 

# Clear packages
p_unload(all)  # Remove all add-ons
detach("package:datasets", unload = TRUE)  # For base

# Clear plots
dev.off()  # But only if there IS a plot

# Clear console
cat("\014")  # ctrl+L

```
