---
title: "R Notebook"
output: html_notebook
---

# LOAD PACKAGES

```{r}

library(datasets)

```

# LOAD DATA

```{r}

head(iris)

```

# BASIC HISTOGRAMS


```{r}
hist(iris$Sepal.Length)

```
```{r}
hist(iris$Sepal.Width)
```
```{r}
hist(iris$Petal.Length)
```

# HISTOGRAM BY GROUP
```{r}
# Put graphs in 3 rows and 1 column
par(mfrow = c(3, 1))
# Histograms for each species using options
hist(iris$Petal.Width [iris$Species == "setosa"],
  xlim = c(0, 3),
  breaks = 9,
  main = "Petal Width for Setosa",
  xlab = "",
  col = "red")

hist(iris$Petal.Width [iris$Species == "versicolor"],
  xlim = c(0, 3),
  breaks = 9,
  main = "Petal Width for Versicolor",
  xlab = "",
  col = "purple")

hist(iris$Petal.Width [iris$Species == "virginica"],
  xlim = c(0, 3),
  breaks = 9,
  main = "Petal Width for Virginica",
  xlab = "",
  col = "blue")

```
# CLEAN UP

```{r}
# Clear packages
detach("package:datasets", unload = TRUE)  # For base
```



```{r}
# Clear console
cat("\014")  # ctrl+L
```






