---
title: "R Notebook"
output: html_notebook
---

#importing data

```{r}
library(datasets)  # Load base packages manually

# Installs pacman ("package manager") if needed
if (!require("pacman")) install.packages("pacman")

# Use pacman to load add-on packages as desired
pacman::p_load(pacman, rio) 

# From the official R documentation
browseURL("http://j.mp/2aFZUrJ")

```

```{r}
# IMPORTING WITH RIO

# CSV
rio_csv <- import("C:/Users/Lenovo/Desktop/R/R_Programming_Tutorial/mbb.csv")
head(rio_csv)


```
```{r}

# TXT
rio_txt <- import("C:/Users/Lenovo/Desktop/R/R_Programming_Tutorial/mbb.txt")
head(rio_txt)

```

```{r}
# Excel XLSX
rio_xlsx <- import("C:/Users/Lenovo/Desktop/R/R_Programming_Tutorial/mbb.xlsx")
head(rio_xlsx)
```

```{r}
View(rio_csv)
```

```{r}
# TEXT FILES

r_txt1 <- read.table("C:/Users/Lenovo/Desktop/R/R_Programming_Tutorial/mbb.txt",
                     header = TRUE, 
                     sep = "\t")


```

```{r}
# READ.CSV FOR CSV FILES

# Don't have to specify delimiters for missing data
# because CSV means "comma separated values"

trends.csv <- read.csv("C:/Users/Lenovo/Desktop/R/R_Programming_Tutorial/mbb.csv", header = TRUE)

```

```{r}
# Clear environment
rm(list = ls()) 

# Clear packages
p_unload(all)  # Remove all add-ons

# Clear console
cat("\014")  # ctrl+L

```