---
title: "R Notebook"
output: html_notebook
---

#Factors

Factors -> in R Programming Language are data structures that are implemented to categorize the data or represent categorical data and store it on multiple levels. 

```{r}

# CREATE DATA

(x1 <- 1:5)
(y  <- 1:10)

# Combine variables
(df1 <- cbind.data.frame(x1, y))
typeof(df1$x1) #integer
str(df1)

```

```{r}
# AS.FACTOR

(x2  <- as.factor(c(1:5)))
(df2 <- cbind.data.frame(x2, y))
typeof(df2$x2)
str(df2)

```

```{r}
# DEFINE EXISTING VARIABLE AS FACTOR

x3  <- c(1:5)
df3 <- cbind.data.frame(x3, y)
(df3$x3 <- factor(df3$x3,
  levels = c(1, 2, 3, 4, 5)))
typeof(df3$x3)
str(df3)

```

```{r}
# LABELS FOR FACTOR 

x4  <- c(1:5)
df4 <- cbind.data.frame(x4, y)
df4$x4 <- factor(df4$x4,
  levels = c(1, 2, 3, 4, 5),
  labels = c("buse", "ayse", "nur", "murat", "sevgi"))
df4
typeof(df4$x4)
str(df4)


```

```{r}
# ORDERED FACTORS AND LABELS

x5  <- c(1:3)
y <- c(1:9)
df5 <- cbind.data.frame(x5, y)
(df5$x5 <- ordered(df5$x5,
  levels = c(3, 1, 2),
  labels = c("No", "Maybe", "Yes")))
df5
typeof(df5$x5)
str(df5)


```
```{r}
# CLEAN UP 

# Clear environment
rm(list = ls()) 

# Clear console
cat("\014")  # ctrl+L

```